### ISSUE TITLE
백엔드 기본 세팅

### ISSUE THREAD

**Issue by Lavegaa** [Lavegaa/i18n-json-generator#1]
# TODO
- [x] fastify 기본 설정
- [x] local postgresql과 연동
- [x] prettier format on save 설정하기
- [ ] fasity-cli로 실행할 때 오류 생김 -> nodemon으로 실행중

https://dev.to/kenwanjohi/fastify-and-postgresql-rest-api-2f9l
